### ISSUE TITLE
Feature request: expand on mouse hover

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#1]
It would be nice to have such option (with configurable delay probably)

**Comment by Feuerfuchs** [comment]
Just to clarify: Do you mean hover on just the expand/collapse button, or hover on the entire applet?

**Comment by Roman-Skripka** [comment]
I think the second option will be better, but all active applications shouldn't move to the left as some of them do now when I click expand button.

**Comment by Feuerfuchs** [comment]
> but all active applications shouldn't move to the left as some of them do now when I click expand button.

You mean the context menu? Unfortunately, I don't have control over that since Cinnamon controls how menus are displayed (i.e. their top left corner is aligned to the applet's center).

**Comment by Roman-Skripka** [comment]
If you do not control the order, in which icons appear in your applet, then it's ok to add instant expand on hover over expand button and collapse back after some configurable delay when the mouse is not in the applets area

**Comment by Roman-Skripka** [comment]
@Feuerfuchs just to be on the same page, I mean that for example thunderbird icon should stay along with skype icon, and not to move to the left after expand action as you can see on the screenshot below
![image](https://cloud.githubusercontent.com/assets/7115589/17740785/7803fbbc-64a2-11e6-90de-e5844412a17f.png)

**Comment by Feuerfuchs** [comment]
That makes sense. :) I can try to implement that, but there's one small problem: There are two types of icons, tray icons and app indicators. For technical reasons, they are in two separate containers, so if I put all hidden icons on the left side of their respective container, that would leave two groups of icons, and one of them might still move if you expand the tray. Is that okay for you?

**Comment by Roman-Skripka** [comment]
From my user's point of view your applet works with tray icons only) So, I'm leaving implementation details to you.
And, as I mentioned above, one more separate useful feature will be to collapse applet after configurable delay.

**Comment by Feuerfuchs** [comment]
> From my user's point of view your applet works with tray icons only) So, I'm leaving implementation details to you.

It's an implementation detail that results in behavior that to users might look like a bug, though. ;) 

Anyway, I implemented the setting and also the automatic expand/collapse on hover in bb6193e. Thanks a lot for your requests! :)
