### ISSUE TITLE
Bug: expand stopped working

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#10]
After a few hours of usage, I've noticed that expand stopped working. The expand icon changes, but nothing appears. Glass log for expand-hide action (version 0555b1a1aa6a0d93db0b183c688b950c10156670):
info t=2016-08-19T15:26:07Z [collapsible-systray@feuerfuchs.eu] Showing icon chromium-browser - instances: 1
info t=2016-08-19T15:26:07Z [collapsible-systray@feuerfuchs.eu] Showing icon teamviewer - instances: 1
info t=2016-08-19T15:26:07Z [collapsible-systray@feuerfuchs.eu] Showing icon thunderbird - instances: 1
info t=2016-08-19T15:26:07Z [collapsible-systray@feuerfuchs.eu] Showing icon skype - instances: 1
info t=2016-08-19T15:26:07Z [collapsible-systray@feuerfuchs.eu] Showing icon swt - instances: 1
info t=2016-08-19T15:26:07Z [collapsible-systray@feuerfuchs.eu] Showing icon skypeforlinux - instances: 2
info t=2016-08-19T15:26:07Z [collapsible-systray@feuerfuchs.eu] Showing icon viberpc - instances: 1
info t=2016-08-19T15:26:07Z [collapsible-systray@feuerfuchs.eu] Showing icon mintupdate.py - instances: 1
info t=2016-08-19T15:26:10Z [collapsible-systray@feuerfuchs.eu] Hiding icon chromium-browser - instances: 1
info t=2016-08-19T15:26:10Z [collapsible-systray@feuerfuchs.eu] Hiding icon teamviewer - instances: 1
info t=2016-08-19T15:26:10Z [collapsible-systray@feuerfuchs.eu] Hiding icon swt - instances: 1
info t=2016-08-19T15:26:10Z [collapsible-systray@feuerfuchs.eu] Hiding icon mintupdate.py - instances: 1

**Comment by Roman-Skripka** [comment]
Not sure why this happened, I'll restart cinnamon and keep an eye if this will reproduce.

**Comment by Feuerfuchs** [comment]
I'll close this for now because the code has changed a lot since the version you used there.
