### ISSUE TITLE
Bug: expand animation causes misclick to random collapsed app

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#12]
When I click active application icon in a moment when expand action triggers (hover), random icon from collapsed list receives that click despite the fact that icons don't move visually.

**Comment by Feuerfuchs** [comment]
I could fix this behavior somewhat by putting the hidden icons below the visible icons. However, under some circumstances the icons might still be accidentally clicked, but that's nothing I could change because of the way Cinnamon displays tray icons.
