### ISSUE TITLE
Expanding "jumps" to far to the left

### ISSUE THREAD

**Issue by Pandiora** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#13]
I'm unsure if this is made by design, but the point where it jumps is between visible and hidden apps. So when I click expand the hidden apps get visible, then it expands 10-20 pixel to far to the left and the before hidden apps with it and after this they go back into the "normal position" and stay there. This behaviour is reproducable everytime on expand.

I'm on Linux Mint 18 Cinnamon, used the bugged "System Tray Collapsible" before and if this behaviour isn't intended it could be a bug due to hidden icon which doesn't show with or without systray and of which I don't know anything. This "unkown app" appeared one time before in "System Tray Collapsible", then I removed it and I thought it was gone. So maybe it is just a hint.

**Comment by Feuerfuchs** [comment]
I'm aware of a bug that the expand animation jumps if you previously changed the setting "Padding of tray icons". Is this how you encountered this issue? If not, is there a way for me to replicate it?

**Comment by Pandiora** [comment]
Yes, you're right, I changed the padding one time. I removed the applet and installed it again now and the tray expands without jumping now. Thank you!

Edit: It happens again without changing the padding. (I just changed the automatic collapsing when inactive to 1s) It looks like there is a problem with icon resizing.

Edit2: Found the problem. When "Allow cinnamon to modify icons and taskbar-texts" (or something like this, mine is in german - you can find it under Taskbar-Settings) is activated, the icons on one hand have different sizes and on the other hand this "jumping-problem" appears. When I deactivate it the icons look nearly the same in height and width and this problem doesn't occurs. Maybe you can try, test and reproduce this. (I'm using a custom-height for the taskbar)

**Comment by Feuerfuchs** [comment]
Ah, I didn't see your edits until just now. However, I just checked if my fix also solves the other issue you described and that seems to be the case. :)

**Comment by Pandiora** [comment]
Alright, I updated to 1.6 and the bug is gone like you said. Thanks in advance.
