### ISSUE TITLE
Bug: Systray Never Collapses

### ISSUE THREAD

**Issue by cwesson** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#15]
The applet starts up collapsed, and keeps icons hidden correctly.  But after clicking the arrow to expand or hovering to expand, the systray will never collapse again.  Un-hover doesn't collapse the tray automatically, and clicking the arrow to collapse it doesn't work.

I'm using Cinnamon 3.0.7 on Fedora 24 with Collapsible Systray 1.6.

**Comment by Feuerfuchs** [comment]
Can you please post the contents of the file ~/.cinnamon/glass.log?

And please be sure the bug has been triggered before you do so, i.e. first expand the tray, then try to collapse it, and if that doesn't work, fetch the log's content.

**Comment by cwesson** [comment]
Logged in, expanded the tray, tried collapsing.  Log attached.
[glass.log.txt](https://github.com/Feuerfuchs/Collapsible-Systray-Cinnamon-Applet/files/560678/glass.log.txt)

**Comment by Feuerfuchs** [comment]
```
info t=2016-10-30T19:30:24.227Z [collapsible-systray@feuerfuchs.eu] Register instance of 
info t=2016-10-30T19:30:24.228Z [collapsible-systray@feuerfuchs.eu] Insert menu item for  in active applications
warning t=2016-10-30T19:30:24.230Z Invalid menu: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar'
```

I don't know if that warning plays a role, but in any case you apparently use an application whose tray icon has no name (= empty string). This interferes with the way the applet keeps track of the icon's visibility state and whether an application is active or not.

The only solution I see here is to assign a default name if the icon doesn't have a valid one. The offending application's menu item (in the context menu) will just be displayed as "[default]" or something like that, but there is really no other way to find out the correct name.

**Comment by cwesson** [comment]
I think that might be the Dropbox client.  My other icons seem to have the right names, the last one ("unknown") is KeePass.  I'll try disabling Dropbox and let you know.

Edit: Yep, that was it.  With Dropbox disabled, the systray expands and collapses correctly.
[glass.log.txt](https://github.com/Feuerfuchs/Collapsible-Systray-Cinnamon-Applet/files/560688/glass.log.txt)
