### ISSUE TITLE
Icons doesn't show up in collapsed Systray

### ISSUE THREAD

**Issue by Pandiora** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#17]
I can add more information for debug later if wanted, but I want to leave this here, since the problem (topic) was discovered multiple times by me.

I can give you a  short test-example:
- PC starts and the application Remmina gets loaded automatically
- closing (exit) Remmina will remove the Icon from Systray
- Opening Remmina again will not show the Icon until I reload Cinnamon
- Remmina is part of the collapsed part of your applet and correctly listed in the "Active Applications"-Menu
- I'm using a custom icon-theme (Oranchelo)

**Same problem from other issue:**

Recently I installed shutter and was using it now and discovered the tray-icon isn't shown and this way not usable if I wanna open Shutter again. All I can see in the logs is this Standard-Output:

`info t=2017-02-08T02:33:25.622Z [collapsible-systray@feuerfuchs.eu] Insert menu item for shutter in inactive applications info t=2017-02-08T02:33:36.267Z Adding systray: shutter (24x24px) info t=2017-02-08T02:33:36.267Z Adding systray: shutter (24x24px) info t=2017-02-08T02:33:37.268Z [collapsible-systray@feuerfuchs.eu] Event: _insertStatusItem - shutter info t=2017-02-08T02:33:37.269Z [collapsible-systray@feuerfuchs.eu] Register instance of shutter info t=2017-02-08T02:33:37.272Z [collapsible-systray@feuerfuchs.eu] Insert menu item for shutter in active applications`

The problem here is, I patched Shutter to a newer version to have Imgur-OAuth-Support by applying patches from AUR-Repository. After patching this problem occured and can only be fixed by moving Shutter to "Inactive Applications" (will be working at this point) and back to "Active Applications" or by reloading Cinnamon. Since the Icon can be usable then maybe you can find a fix for it. I also try to find some fix on my own.

**Comment by Feuerfuchs** [comment]
Thanks for the report, I'll look into it! But please be aware that it might take a while because I have exams at the moment.

**Comment by Pandiora** [comment]
No hurry, your exams are more important, work on it when you have more spare time. Thanks.

**Comment by Feuerfuchs** [comment]
Thanks for reminding me of this problem, I actually forgot about it.

So there are some noteworthy things about this bug which strongly indicate that the actual issue is Cinnamon. I had used my system tray for the past few months and I actually had massive issues with icons becoming invisible and overall behaving erratically.
  Then, a few weeks ago, I reinstalled my system for unrelated reasons and since then, my applet has been working perfectly fine. No issues _at all_, and I just now tried to reproduce the behaviour you described in the first part of your comment to no avail.

So I think that the actual reason for this problem is Cinnamon itself. Perhaps it was caused by an update to a new major version or it just happens over time due to a bug, I don't know.
  Anyway, I'm afraid I can't fix a problem that doesn't exist for me anymore and actually might be out of scope. Maybe reinstalling your system (or testing the applet in a clean install on a VM) will fix the problem for you as well?

**Comment by Pandiora** [comment]
You're right, I forgot to add that Remmina is working fine for me now and it seems like only shutter is causing such problems. I didn't changed much on my system since I reported this bug, except for updating Mint to Serena and this way also updated cinnamon. I don't really want to reinstall my system, but with your feedback I have a better direction to search for a workaround now (like reinstalling shutter). I will report back if I can solve this problem.

**Comment by Pandiora** [comment]
Alright, this was easy to find. Reinstalled shutter (now it is unpatched by me) and the icon shows up after a short time. I have no idea how a patch-file which just patches oauth-modules can break the systray-icon, but the "bug" should be solved now and isn't related to your applet and like you said -> cinnamon.

Edit: context-menu works too

Edit2: Now I found something interesting while checking for the version of shutter (shutter --version)
```
WARNING: gnome-web-photo is missing --> screenshots of websites will be disabled!

WARNING: Image::ExifTool is missing --> writing Exif information will be disabled!

WARNING: Gtk2::AppIndicator is missing --> there will be no icon showing up in the status bar when running Unity!
```

I will look into it and how to fix it.
Fix for missing tools `sudo apt-get install libimage-exiftool-perl gnome-web-photo`
Not needed, but to fix the warning for AppIndicator `sudo apt-get install libgtk2-appindicator-perl`

Now to patch shutter (so Imgur works) just clone the [AUR git](https://aur.archlinux.org/packages/shutter/?comments=all) which includes several patches and also download shutter from dev-website, then apply patch for imgur:
```
cd ~/Downloads
git clone https://aur.archlinux.org/shutter.git
wget http://shutter-project.org/wp-content/uploads/releases/tars/shutter-0.93.1.tar.gz && tar -xzf shutter-0.93.1.tar.gz
sudo cp -R ~/Downloads/shutter-0.93.1/share/shutter/resources/modules /usr/share/shutter/resources/
cd shutter
sudo cp fix-imgur.patch /usr
cd /usr
sudo patch -p0 < fix-imgur.patch
```

Now clean up, if this is the only patch we need:
```
sudo rm -r ~/Downloads/shutter
sudo rm -r ~/Downloads/shutter-0.93.1
```

This way the bug with the missing icon shouldn't be triggered, even if shutter got patched. Issue is solved for me now.
