### ISSUE TITLE
Remove icon highlighting

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#2]
When I hover a mouse, icons get highlighted. With a random delay (other applets themselves are highlighted instantly). It's irritating and useless behavior.
![image](https://cloud.githubusercontent.com/assets/7115589/17739562/3ee43f08-649e-11e6-8646-497db8c8171c.png)
Additionally, sometimes, more than 1 icon can be highlighted at the same time (just noticed this bug).

**Comment by Feuerfuchs** [comment]
I added a setting to disable the hover effect in bb6193e
