### ISSUE TITLE
Applet not compatible with Cinnamon 3.6.2

### ISSUE THREAD

**Issue by Pandiora** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#22]
Today (I'm on Arch Linux [Manjaro]) now, I updated my system and Cinnamon got updated too. Some apps disappeared from my taskbar, including yours and my own, some applets still work, like IcingTaskManager. Since I updated my own applet (i.e. using layout in settings-schema.json) and comparing your and my Applet to IcingTaskManager, I'm wondering what could be the problem here.

- xsession-errors doesn't give any error
- glass.log prints `No JS module 'applet' found in search path` and `collapsible-systray@feuerfuchs.eu/3.2/applet.js:1:7`

I'm still trying to find a solution and hopefully can solve this fast on my own.

**Edith:** I can't wrap my head around what I'm actually missing and I don't know how to debug this. I already checked the logs, removed the applet (and config-folder also), did some changes, like removing the uuid-import and instead writing it as string, added several keywords+values to manifest.json, added folders for different versioning and so on, nothing seems to work. After I downgraded to Cinnamon 3.4 now (only this package) the applet works again. I can't find the blogpost I were reading lately, but it stated LM-Devs changed something depending GJS/CJS and how every applet uses its own process now. I also checked if we import some module other applets don't, but one can guess ... nope. The file-structure also seems to be fine, since Cinnamon is at least finding the applet.js and all other needed data. Maybe I'll try again later to find a solution.

**Comment by Feuerfuchs** [comment]
Thanks for letting me know! I just updated Cinnamon myself and will try to find a solution now.

**Comment by Feuerfuchs** [comment]
Looks like the fix was pretty easy in my case: b210d46
I hope my commit helps you find a solution for your own applet.

**Comment by Pandiora** [comment]
Nice, @jashix informed me about this change too: https://github.com/linuxmint/Cinnamon/pull/6790. Pretty easy to solve, thanks for your fast response.
