### ISSUE TITLE
Collapsing/expanding the system tray makes applets shake

### ISSUE THREAD

**Issue by telmotrooper** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#24]
Since I find it kinda hard to explain the issue, I made a short video to make it clear:
https://drive.google.com/open?id=1hfESf6jShpIFQ2wlyu0I09FyaefKqYi3

I'm on Cinnamon 3.6.6. By the way, I'm having this issue since the last update that made the applet work on Cinnamon 3.6+.

**Comment by Feuerfuchs** [comment]
Yeah, I've noticed this issue as well. I'm not sure how to fix it yet, but I'll work on it.

**Comment by telmotrooper** [comment]
Thank you for your swift response.
I might give it a look myself given the time, since it seems to be pretty much all JS. :)
