### ISSUE TITLE
Inactive applications icons duplication

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#3]
Not sure what this section is made for, but something definitely went wrong :)
![image](https://cloud.githubusercontent.com/assets/7115589/17740137/35d29b74-64a0-11e6-9a6b-590376bbd133.png)

**Comment by Feuerfuchs** [comment]
Wow, I have no explanation for this. Does that still happen with v1.1?

**Comment by Roman-Skripka** [comment]
I'm not sure how this happened, but I don't see such behavior with 1.1. Can be closed until happens again.

**Comment by Feuerfuchs** [comment]
Thank god. I improved the menu handling in v1.1 drastically so it would've sucked if this bug still occurred.
