### ISSUE TITLE
Problem on Skype Tray Icon

### ISSUE THREAD

**Issue by DanielRios549** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#30]
After update from Mint 18.3 to 19, the applet now shows incorrectly the Skype tray icon, this didn't happen on Mint 18.3, only on Mint 19, all others icons are ok (Flameshot is a little bit bigger, but it's ok), only Skype icon is bad. And this does not happen on default Cinnamon tray applet, maybe an update is causing this.
![2018-08-03_21-54](https://user-images.githubusercontent.com/11152535/43670917-2a94c05a-9768-11e8-96bd-e314cb6086d0.png)

**Comment by Feuerfuchs** [comment]
Tested and confirmed. Thanks for reporting!

**Comment by DanielRios549** [comment]
@Feuerfuchs The bugfix does not work, and this bug persists after the last update, are you you working on a global fix? I asking that because I think it happens only with small icons, probably 16x16 px, and or me, only Skype and Musicxmatch have this bug.

**Comment by Feuerfuchs** [comment]
It seems I completely forgot to send the update to the Cinnamon Spices repository. Sorry about the delay.

As for Musicxmatch, I'm not familiar with it and I couldn't find anything in the Arch repositories. How can I test this bug?

**Comment by DanielRios549** [comment]
This is so, so strange man, it still have this bug on Skype icon, but about Musixmatch, even the System Tray Applet is no showing incorrectly, I think there is a problem on Cinnamon about this... Here is the System Tray and Collapsible Systray prints, you can see that the Skype icon is a little smaller

![2018-09-24_20-41](https://user-images.githubusercontent.com/11152535/45985047-b90be200-c03a-11e8-8e91-746a56b4e170.png)
![2018-09-24_20-42](https://user-images.githubusercontent.com/11152535/45985051-bf9a5980-c03a-11e8-84ad-a2d36c5746a1.png)
