### ISSUE TITLE
Cinnamon 4 support

### ISSUE THREAD

**Issue by telmotrooper** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#32]
It seems Cinnamon 4.0.0 was released on Arch and it broke collapsible systray...

If I remember well, @Feuerfuchs, you said you usually wait for the update on Mint before issuing a fix. Is that right?

**Comment by Feuerfuchs** [comment]
Yeah, I have to wait until it lands in the Manjaro (rather than Linux Mint) repositories. Hopefully, it won't take long!

**Comment by telmotrooper** [comment]
No problem! Thanks for the answer.
Have you considered using Antergos, by the way?

**Comment by Feuerfuchs** [comment]
Yes, I actually had tried it but I hit some problems with the Nvidia drivers (nouveau and proprietary) and couldn't use the system once it was installed. I don't remember the specifics.

Anyway, I don't mind the delayed package updates in Manjaro — actually, it's the opposite. They use the delay for some additional testing to make sure things work smoothly, and it shows. I haven't had any major problems after updating for 3 years now.

**Comment by Feuerfuchs** [comment]
Alright, it's there now and it mostly works fine if I add 4.0 to the list of compatible Cinnamon versions. The only thing that's screwed up are icon sizes.

**Comment by Feuerfuchs** [comment]
Pull request: https://github.com/linuxmint/cinnamon-spices-applets/pull/2056

**Comment by telmotrooper** [comment]
Thank you very much!
