### ISSUE TITLE
Bug: collapsing after fast expand

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#4]
If I click on a expand button/hover over applet area and move out cursor fast, it will never automatically collapse back.
I'm using the configuration below.
![image](https://cloud.githubusercontent.com/assets/7115589/17767820/3879761e-653a-11e6-8469-32cefac24866.png)
BTW, what is 'Delay until initial collapse' made for? It's not clear. If possible please add some help on options if configuration allows it or add description in readme.

**Comment by Feuerfuchs** [comment]
Fixed, and I added tooltips and improved some captions in the settings.
