### ISSUE TITLE
Bug: inactive application which is actually active

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#5]
If more than one instance of application was opened, and one of them was closed, then despite the fact that there are still active instances of this application, it's marked as inactive.
Find skypeforlinux below.
![image](https://cloud.githubusercontent.com/assets/7115589/17768677/b79ab37e-653d-11e6-9c0a-09a56b714a31.png)

**Comment by Feuerfuchs** [comment]
Multiple instances are supported now. :)
