### ISSUE TITLE
Feature request: Apps sorting

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#6]
I've just noticed that after each time I restart cinnamon, the tray icons appear in random order!
Is it possible to add selection option to have 'alphabetical sorting' or 'in order they appear' (not sure if this is how it now works)?
Many thanks!

**Comment by Feuerfuchs** [comment]
For the active/inactive application menus? Yeah, I'll add that. :)
(And you're right, right now the menu items are added in the order they're pushed to the applet)

**Comment by Roman-Skripka** [comment]
I think this option should configure the both menus at the same time.

**Comment by Roman-Skripka** [comment]
@Feuerfuchs doesn't seem to work when there are 2 identical app icons
![image](https://cloud.githubusercontent.com/assets/7115589/17848702/8d1e21f8-685d-11e6-986e-bdbb06077591.png)

**Comment by Feuerfuchs** [comment]
I only implemented sorting for the menus, so you wanted the icons to be sorted as well?

**Comment by Roman-Skripka** [comment]
Yes, this is what was my initial request about )
