### ISSUE TITLE
Bug: collapsed icons are cached

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#7]
If the application's icon is hidden and this application updates the icon (e.g. new message came), then the icon doesn't get an update. For non-collapsed icons it works fine.

**Comment by Feuerfuchs** [comment]
I don't use any applications that change their icons often, so I had to find a fix blindly. Can you please try if it the bug is still there? (The changes are currently only on GitHub)

**Comment by Feuerfuchs** [comment]
Installed Pidgin and tried it myself — didn't fix it. :(

**Comment by Roman-Skripka** [comment]
Yeah, just checked it myself. New bug appeared - moving app from active list to collapsed one closes settings menu

**Comment by Roman-Skripka** [comment]
Not sure if it was made by intention, but active app icons stopped updating as well )

**Comment by Feuerfuchs** [comment]
I've been looking for a solution for hours now, but nothing works. I can only conclude that Cinnamon's way of handling tray icons is very bugged.
The only solution I can come up with is to remove animations and reload all tray icons if the user expands/collapses the tray. Looks ugly, but it eliminates this bug.

**Comment by Feuerfuchs** [comment]
Alright, I just found a semi-working solution. Hidden icons will keep working now, but there are some exceptions. 1: Chromium is only a quarter disk; 2: If the Pidgin icon starts blinking, it just disappears. Hiding and un-hiding it while it's not blinking fixes that (until it blinks again).
Still, this solution is way more acceptable than reloading all icons as it allows me to keep animations. :)

**Comment by Feuerfuchs** [comment]
And now the solution is complete. :) Depending on the application I use different methods to hide the icon. This way, I could fix Pidgin and Chromium.

Please let me know if there are still some icons that don't behave correctly!

**Comment by Roman-Skripka** [comment]
Well, as a developer, I don't think that having a list of apps-exclusions is the right way to handle issues like that. And after this fix I have awt app quarted, the same I think can happen to chromium-browser(chrome?) icon.
One more bug - moving the app to the list of collapsed apps not only reloads the whole applet, but also makes other icons there invisible until applet's reload.
If the root cause lies in cinnamon implementation, I think you should report about it to their bug tracker.
P.S. at least skype icons work as expected if collapsed and this is great

**Comment by Roman-Skripka** [comment]
To track issue with applet's reload on settings change https://github.com/Feuerfuchs/Collapsible-Systray-Cinnamon-Applet/issues/8

**Comment by Feuerfuchs** [comment]
> Well, as a developer, I don't think that having a list of apps-exclusions is the right way to handle issues like that

I don't like it either, but I don't have much of a choice. Even the Cinnamon developers themselves handled it like that, just take a look at this code: https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/systray%40cinnamon.org/applet.js#L275-#L297

I'll open an issue, but it seems these problems are all related to the one described in this file: https://github.com/linuxmint/Cinnamon/blob/master/src/cinnamon-embedded-window.c
But let's see if they can find a solution...

> awt app quarted

Does the applet show the name as "awt"? (I need this to add it to the exception list)

**Comment by Roman-Skripka** [comment]
@Feuerfuchs sorry, I made a typo, it appears in settings as 'swt'.

**Comment by Roman-Skripka** [comment]
To track the issue with missing icons https://github.com/Feuerfuchs/Collapsible-Systray-Cinnamon-Applet/issues/9

**Comment by Feuerfuchs** [comment]
I am now investigating a new method to display icons. Let's hope this one will solve all issues and I won't have to maintain an exclusion list. :S

**Comment by Feuerfuchs** [comment]
Today I tried a lot of things to make icons work properly, but it seems there's no way to get around the exception lists. My efforts aren't wasted, though – the code is now considerably better.

**Comment by Feuerfuchs** [comment]
I reported the issue now: https://github.com/linuxmint/Cinnamon/issues/5573
Let's hope the developers there find a solution.

**Comment by ghost** [comment]
@Feuerfuchs do you have a better idea of how this will work? I think it's nice they don't update while they are hidden. I only think in one better solution that re-add the icons... This is create a refresh function inside the cinnamon api if not exist... Do you search for something like Refresh?

**Comment by ghost** [comment]
I dont't know if you speak about the cinnamon systray icons or the indicators... They sure will need different solutions...

**Comment by Feuerfuchs** [comment]
@lestcape App indicators don't have any issues since they use the proper API (e.g. ClutterImage) to display the icons.
Tray icons, however, are displayed by using an invisible GtkWindow whose content is composed onto the desktop using a special ClutterTexture. That solution seems to have some issues, such as that icons aren't updated anymore as soon as they become invisible, and the only way to make them work again is to completely reload them.
So what I need is either a fix for this problem, or some way to make icons work again _after_ they have stopped updating without reloading them entirely.

**Comment by ghost** [comment]
I can only help for app indicators because it's what i merged in cinnamon, but i know you are right.... Do you test this: https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/systray%40cinnamon.org/applet.js#L228?

**Comment by Feuerfuchs** [comment]
That line of code you linked reloads all tray icons completely, and that's what I don't want to do. The only time I could reload all icons to make them work again would be after the expand animation, so what the user would see is that all icons suddenly disappear as soon as the animation is finished and re-appear after one or two seconds — that wouldn't look good at all. :/

**Comment by ghost** [comment]
Ok, but see, this is the way of how the thing are... what you need is a change of the api or found a work around, but tray icons works in this way...

**Comment by Feuerfuchs** [comment]
And that is why I posted an issue is the Cinnamon repository — to have the developers take a look if they can change "the way of how things are". Surely it can't be intentional behavior for tray icons to stop updating if their actor becomes invisible?

**Comment by ghost** [comment]
I don't know if was or not an intentional behaviour... The embedded GtkIncons come from Cinnamon.TrayManager implementation. In the cjs part there are not anything relate with that:
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/statusIconDispatcher.js

You need to search in the C++ class if there are something like that, But could be also a behavior of the embedded actors and not a systray specific. Like the systray provide the only embedded icons in cinnamon i don't have a point to compare...

I also don't know where is implemented the TrayManager, if i found where it's i will say you...

**Comment by Feuerfuchs** [comment]
I'm not sure what your point is. I'm not looking for a solution anymore, I'm just waiting for what the Cinnamon developers can say about the matter.

**Comment by ghost** [comment]
My point is that you can find the solution to this problem like any cinnamon dev. Wait for the cinnamon devs it's not an option... You could be a cinnamon devs if you want... Just find a good solution for that and create a pull request to solve the issue... But of course if this is not your intention you can wait if you want...

**Comment by Feuerfuchs** [comment]
If I didn't have exams currently I would've done that, but right now it doesn't seem like a good idea to learn how Cinnamon works and set up my computer for debugging and whatnot. ^^

**Comment by Feuerfuchs** [comment]
Besides, I actually did take a look at the C files and pointed to a possible explanation for the issues (see my issue in the Cinnamon repository). But I really can't do more than that ATM.
