### ISSUE TITLE
Changing the settings of active/inactive apps reloads applet

### ISSUE THREAD

**Issue by Roman-Skripka** [Feuerfuchs/Collapsible-Systray-Cinnamon-Applet#8]
As a user, I don't want to have the whole applet reloaded, because the settings balloon disappears and I have to launch it again to change the settings of each app.

**Comment by Feuerfuchs** [comment]
Not really a bug since I implemented it to act that way. But I improved it now so changing settings doesn't reload all tray icons anymore. :)
